spring.application.name=filmorate
logging.level.root=INFO
logging.level.ru.yandex.practicum=DEBUG
server.port=8080
spring.devtools.restart.enabled=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.hibernate.ddl-auto=update
spring.cors.allowed-origins=*
spring.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS