-- ============================================
-- Filmorate: схема
-- ============================================

CREATE TABLE IF NOT EXISTS mpa (
                                   id          BIGINT PRIMARY KEY,
                                   name        VARCHAR(10) NOT NULL UNIQUE,
    description VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS genres (
                                      id   BIGINT PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS users (
                                     id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(50)  NOT NULL UNIQUE,
    name     VARCHAR(100),
    birthday DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
                                     id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name          VARCHAR(200) NOT NULL,
    description   VARCHAR(200),
    release_date  DATE NOT NULL,
    duration      INTEGER NOT NULL CHECK (duration > 0),
    mpa_rating_id BIGINT REFERENCES mpa(id)
    );

CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id  BIGINT NOT NULL REFERENCES films(id)  ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS friendships (
                                           user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    friend_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status    VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED')),
    PRIMARY KEY (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS likes (
                                     film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

CREATE INDEX IF NOT EXISTS idx_likes_film_id ON likes(film_id);
CREATE INDEX IF NOT EXISTS idx_likes_user_id ON likes(user_id);
